// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ocr_protobuf.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ocr_5fprotobuf_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ocr_5fprotobuf_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ocr_5fprotobuf_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ocr_5fprotobuf_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[8]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ocr_5fprotobuf_2eproto;
namespace ocr_protobuf {
class OcrRequest;
class OcrRequestDefaultTypeInternal;
extern OcrRequestDefaultTypeInternal _OcrRequest_default_instance_;
class OcrRequest_PicPaths;
class OcrRequest_PicPathsDefaultTypeInternal;
extern OcrRequest_PicPathsDefaultTypeInternal _OcrRequest_PicPaths_default_instance_;
class OcrResponse;
class OcrResponseDefaultTypeInternal;
extern OcrResponseDefaultTypeInternal _OcrResponse_default_instance_;
class OcrResponse_OcrResult;
class OcrResponse_OcrResultDefaultTypeInternal;
extern OcrResponse_OcrResultDefaultTypeInternal _OcrResponse_OcrResult_default_instance_;
class OcrResponse_OcrResult_ResultPos;
class OcrResponse_OcrResult_ResultPosDefaultTypeInternal;
extern OcrResponse_OcrResult_ResultPosDefaultTypeInternal _OcrResponse_OcrResult_ResultPos_default_instance_;
class OcrResponse_OcrResult_ResultPos_PosXY;
class OcrResponse_OcrResult_ResultPos_PosXYDefaultTypeInternal;
extern OcrResponse_OcrResult_ResultPos_PosXYDefaultTypeInternal _OcrResponse_OcrResult_ResultPos_PosXY_default_instance_;
class OcrResponse_OcrResult_SingleResult;
class OcrResponse_OcrResult_SingleResultDefaultTypeInternal;
extern OcrResponse_OcrResult_SingleResultDefaultTypeInternal _OcrResponse_OcrResult_SingleResult_default_instance_;
class OcrResponse_OcrResult_SingleResult_OneResult;
class OcrResponse_OcrResult_SingleResult_OneResultDefaultTypeInternal;
extern OcrResponse_OcrResult_SingleResult_OneResultDefaultTypeInternal _OcrResponse_OcrResult_SingleResult_OneResult_default_instance_;
}  // namespace ocr_protobuf
PROTOBUF_NAMESPACE_OPEN
template<> ::ocr_protobuf::OcrRequest* Arena::CreateMaybeMessage<::ocr_protobuf::OcrRequest>(Arena*);
template<> ::ocr_protobuf::OcrRequest_PicPaths* Arena::CreateMaybeMessage<::ocr_protobuf::OcrRequest_PicPaths>(Arena*);
template<> ::ocr_protobuf::OcrResponse* Arena::CreateMaybeMessage<::ocr_protobuf::OcrResponse>(Arena*);
template<> ::ocr_protobuf::OcrResponse_OcrResult* Arena::CreateMaybeMessage<::ocr_protobuf::OcrResponse_OcrResult>(Arena*);
template<> ::ocr_protobuf::OcrResponse_OcrResult_ResultPos* Arena::CreateMaybeMessage<::ocr_protobuf::OcrResponse_OcrResult_ResultPos>(Arena*);
template<> ::ocr_protobuf::OcrResponse_OcrResult_ResultPos_PosXY* Arena::CreateMaybeMessage<::ocr_protobuf::OcrResponse_OcrResult_ResultPos_PosXY>(Arena*);
template<> ::ocr_protobuf::OcrResponse_OcrResult_SingleResult* Arena::CreateMaybeMessage<::ocr_protobuf::OcrResponse_OcrResult_SingleResult>(Arena*);
template<> ::ocr_protobuf::OcrResponse_OcrResult_SingleResult_OneResult* Arena::CreateMaybeMessage<::ocr_protobuf::OcrResponse_OcrResult_SingleResult_OneResult>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ocr_protobuf {

// ===================================================================

class OcrResponse_OcrResult_ResultPos_PosXY :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ocr_protobuf.OcrResponse.OcrResult.ResultPos.PosXY) */ {
 public:
  OcrResponse_OcrResult_ResultPos_PosXY();
  virtual ~OcrResponse_OcrResult_ResultPos_PosXY();

  OcrResponse_OcrResult_ResultPos_PosXY(const OcrResponse_OcrResult_ResultPos_PosXY& from);
  OcrResponse_OcrResult_ResultPos_PosXY(OcrResponse_OcrResult_ResultPos_PosXY&& from) noexcept
    : OcrResponse_OcrResult_ResultPos_PosXY() {
    *this = ::std::move(from);
  }

  inline OcrResponse_OcrResult_ResultPos_PosXY& operator=(const OcrResponse_OcrResult_ResultPos_PosXY& from) {
    CopyFrom(from);
    return *this;
  }
  inline OcrResponse_OcrResult_ResultPos_PosXY& operator=(OcrResponse_OcrResult_ResultPos_PosXY&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const OcrResponse_OcrResult_ResultPos_PosXY& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const OcrResponse_OcrResult_ResultPos_PosXY* internal_default_instance() {
    return reinterpret_cast<const OcrResponse_OcrResult_ResultPos_PosXY*>(
               &_OcrResponse_OcrResult_ResultPos_PosXY_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(OcrResponse_OcrResult_ResultPos_PosXY& a, OcrResponse_OcrResult_ResultPos_PosXY& b) {
    a.Swap(&b);
  }
  inline void Swap(OcrResponse_OcrResult_ResultPos_PosXY* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline OcrResponse_OcrResult_ResultPos_PosXY* New() const final {
    return CreateMaybeMessage<OcrResponse_OcrResult_ResultPos_PosXY>(nullptr);
  }

  OcrResponse_OcrResult_ResultPos_PosXY* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<OcrResponse_OcrResult_ResultPos_PosXY>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const OcrResponse_OcrResult_ResultPos_PosXY& from);
  void MergeFrom(const OcrResponse_OcrResult_ResultPos_PosXY& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OcrResponse_OcrResult_ResultPos_PosXY* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ocr_protobuf.OcrResponse.OcrResult.ResultPos.PosXY";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ocr_5fprotobuf_2eproto);
    return ::descriptor_table_ocr_5fprotobuf_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // @@protoc_insertion_point(class_scope:ocr_protobuf.OcrResponse.OcrResult.ResultPos.PosXY)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  float x_;
  float y_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ocr_5fprotobuf_2eproto;
};
// -------------------------------------------------------------------

class OcrResponse_OcrResult_ResultPos :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ocr_protobuf.OcrResponse.OcrResult.ResultPos) */ {
 public:
  OcrResponse_OcrResult_ResultPos();
  virtual ~OcrResponse_OcrResult_ResultPos();

  OcrResponse_OcrResult_ResultPos(const OcrResponse_OcrResult_ResultPos& from);
  OcrResponse_OcrResult_ResultPos(OcrResponse_OcrResult_ResultPos&& from) noexcept
    : OcrResponse_OcrResult_ResultPos() {
    *this = ::std::move(from);
  }

  inline OcrResponse_OcrResult_ResultPos& operator=(const OcrResponse_OcrResult_ResultPos& from) {
    CopyFrom(from);
    return *this;
  }
  inline OcrResponse_OcrResult_ResultPos& operator=(OcrResponse_OcrResult_ResultPos&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const OcrResponse_OcrResult_ResultPos& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const OcrResponse_OcrResult_ResultPos* internal_default_instance() {
    return reinterpret_cast<const OcrResponse_OcrResult_ResultPos*>(
               &_OcrResponse_OcrResult_ResultPos_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(OcrResponse_OcrResult_ResultPos& a, OcrResponse_OcrResult_ResultPos& b) {
    a.Swap(&b);
  }
  inline void Swap(OcrResponse_OcrResult_ResultPos* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline OcrResponse_OcrResult_ResultPos* New() const final {
    return CreateMaybeMessage<OcrResponse_OcrResult_ResultPos>(nullptr);
  }

  OcrResponse_OcrResult_ResultPos* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<OcrResponse_OcrResult_ResultPos>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const OcrResponse_OcrResult_ResultPos& from);
  void MergeFrom(const OcrResponse_OcrResult_ResultPos& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OcrResponse_OcrResult_ResultPos* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ocr_protobuf.OcrResponse.OcrResult.ResultPos";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ocr_5fprotobuf_2eproto);
    return ::descriptor_table_ocr_5fprotobuf_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef OcrResponse_OcrResult_ResultPos_PosXY PosXY;

  // accessors -------------------------------------------------------

  enum : int {
    kPosFieldNumber = 1,
  };
  // repeated .ocr_protobuf.OcrResponse.OcrResult.ResultPos.PosXY pos = 1;
  int pos_size() const;
  private:
  int _internal_pos_size() const;
  public:
  void clear_pos();
  ::ocr_protobuf::OcrResponse_OcrResult_ResultPos_PosXY* mutable_pos(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ocr_protobuf::OcrResponse_OcrResult_ResultPos_PosXY >*
      mutable_pos();
  private:
  const ::ocr_protobuf::OcrResponse_OcrResult_ResultPos_PosXY& _internal_pos(int index) const;
  ::ocr_protobuf::OcrResponse_OcrResult_ResultPos_PosXY* _internal_add_pos();
  public:
  const ::ocr_protobuf::OcrResponse_OcrResult_ResultPos_PosXY& pos(int index) const;
  ::ocr_protobuf::OcrResponse_OcrResult_ResultPos_PosXY* add_pos();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ocr_protobuf::OcrResponse_OcrResult_ResultPos_PosXY >&
      pos() const;

  // @@protoc_insertion_point(class_scope:ocr_protobuf.OcrResponse.OcrResult.ResultPos)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ocr_protobuf::OcrResponse_OcrResult_ResultPos_PosXY > pos_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ocr_5fprotobuf_2eproto;
};
// -------------------------------------------------------------------

class OcrResponse_OcrResult_SingleResult_OneResult :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ocr_protobuf.OcrResponse.OcrResult.SingleResult.OneResult) */ {
 public:
  OcrResponse_OcrResult_SingleResult_OneResult();
  virtual ~OcrResponse_OcrResult_SingleResult_OneResult();

  OcrResponse_OcrResult_SingleResult_OneResult(const OcrResponse_OcrResult_SingleResult_OneResult& from);
  OcrResponse_OcrResult_SingleResult_OneResult(OcrResponse_OcrResult_SingleResult_OneResult&& from) noexcept
    : OcrResponse_OcrResult_SingleResult_OneResult() {
    *this = ::std::move(from);
  }

  inline OcrResponse_OcrResult_SingleResult_OneResult& operator=(const OcrResponse_OcrResult_SingleResult_OneResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline OcrResponse_OcrResult_SingleResult_OneResult& operator=(OcrResponse_OcrResult_SingleResult_OneResult&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const OcrResponse_OcrResult_SingleResult_OneResult& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const OcrResponse_OcrResult_SingleResult_OneResult* internal_default_instance() {
    return reinterpret_cast<const OcrResponse_OcrResult_SingleResult_OneResult*>(
               &_OcrResponse_OcrResult_SingleResult_OneResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(OcrResponse_OcrResult_SingleResult_OneResult& a, OcrResponse_OcrResult_SingleResult_OneResult& b) {
    a.Swap(&b);
  }
  inline void Swap(OcrResponse_OcrResult_SingleResult_OneResult* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline OcrResponse_OcrResult_SingleResult_OneResult* New() const final {
    return CreateMaybeMessage<OcrResponse_OcrResult_SingleResult_OneResult>(nullptr);
  }

  OcrResponse_OcrResult_SingleResult_OneResult* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<OcrResponse_OcrResult_SingleResult_OneResult>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const OcrResponse_OcrResult_SingleResult_OneResult& from);
  void MergeFrom(const OcrResponse_OcrResult_SingleResult_OneResult& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OcrResponse_OcrResult_SingleResult_OneResult* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ocr_protobuf.OcrResponse.OcrResult.SingleResult.OneResult";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ocr_5fprotobuf_2eproto);
    return ::descriptor_table_ocr_5fprotobuf_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOneStrUtf8FieldNumber = 2,
    kOnePosFieldNumber = 1,
  };
  // bytes one_str_utf8 = 2;
  void clear_one_str_utf8();
  const std::string& one_str_utf8() const;
  void set_one_str_utf8(const std::string& value);
  void set_one_str_utf8(std::string&& value);
  void set_one_str_utf8(const char* value);
  void set_one_str_utf8(const void* value, size_t size);
  std::string* mutable_one_str_utf8();
  std::string* release_one_str_utf8();
  void set_allocated_one_str_utf8(std::string* one_str_utf8);
  private:
  const std::string& _internal_one_str_utf8() const;
  void _internal_set_one_str_utf8(const std::string& value);
  std::string* _internal_mutable_one_str_utf8();
  public:

  // .ocr_protobuf.OcrResponse.OcrResult.ResultPos one_pos = 1;
  bool has_one_pos() const;
  private:
  bool _internal_has_one_pos() const;
  public:
  void clear_one_pos();
  const ::ocr_protobuf::OcrResponse_OcrResult_ResultPos& one_pos() const;
  ::ocr_protobuf::OcrResponse_OcrResult_ResultPos* release_one_pos();
  ::ocr_protobuf::OcrResponse_OcrResult_ResultPos* mutable_one_pos();
  void set_allocated_one_pos(::ocr_protobuf::OcrResponse_OcrResult_ResultPos* one_pos);
  private:
  const ::ocr_protobuf::OcrResponse_OcrResult_ResultPos& _internal_one_pos() const;
  ::ocr_protobuf::OcrResponse_OcrResult_ResultPos* _internal_mutable_one_pos();
  public:

  // @@protoc_insertion_point(class_scope:ocr_protobuf.OcrResponse.OcrResult.SingleResult.OneResult)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr one_str_utf8_;
  ::ocr_protobuf::OcrResponse_OcrResult_ResultPos* one_pos_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ocr_5fprotobuf_2eproto;
};
// -------------------------------------------------------------------

class OcrResponse_OcrResult_SingleResult :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ocr_protobuf.OcrResponse.OcrResult.SingleResult) */ {
 public:
  OcrResponse_OcrResult_SingleResult();
  virtual ~OcrResponse_OcrResult_SingleResult();

  OcrResponse_OcrResult_SingleResult(const OcrResponse_OcrResult_SingleResult& from);
  OcrResponse_OcrResult_SingleResult(OcrResponse_OcrResult_SingleResult&& from) noexcept
    : OcrResponse_OcrResult_SingleResult() {
    *this = ::std::move(from);
  }

  inline OcrResponse_OcrResult_SingleResult& operator=(const OcrResponse_OcrResult_SingleResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline OcrResponse_OcrResult_SingleResult& operator=(OcrResponse_OcrResult_SingleResult&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const OcrResponse_OcrResult_SingleResult& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const OcrResponse_OcrResult_SingleResult* internal_default_instance() {
    return reinterpret_cast<const OcrResponse_OcrResult_SingleResult*>(
               &_OcrResponse_OcrResult_SingleResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(OcrResponse_OcrResult_SingleResult& a, OcrResponse_OcrResult_SingleResult& b) {
    a.Swap(&b);
  }
  inline void Swap(OcrResponse_OcrResult_SingleResult* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline OcrResponse_OcrResult_SingleResult* New() const final {
    return CreateMaybeMessage<OcrResponse_OcrResult_SingleResult>(nullptr);
  }

  OcrResponse_OcrResult_SingleResult* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<OcrResponse_OcrResult_SingleResult>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const OcrResponse_OcrResult_SingleResult& from);
  void MergeFrom(const OcrResponse_OcrResult_SingleResult& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OcrResponse_OcrResult_SingleResult* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ocr_protobuf.OcrResponse.OcrResult.SingleResult";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ocr_5fprotobuf_2eproto);
    return ::descriptor_table_ocr_5fprotobuf_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef OcrResponse_OcrResult_SingleResult_OneResult OneResult;

  // accessors -------------------------------------------------------

  enum : int {
    kOneResultFieldNumber = 4,
    kSingleStrUtf8FieldNumber = 2,
    kSinglePosFieldNumber = 1,
    kUnknownPosFieldNumber = 10,
    kSingleRateFieldNumber = 3,
    kLxFieldNumber = 5,
    kLyFieldNumber = 6,
    kRxFieldNumber = 7,
    kRyFieldNumber = 8,
    kUnknown0FieldNumber = 9,
  };
  // repeated .ocr_protobuf.OcrResponse.OcrResult.SingleResult.OneResult one_result = 4;
  int one_result_size() const;
  private:
  int _internal_one_result_size() const;
  public:
  void clear_one_result();
  ::ocr_protobuf::OcrResponse_OcrResult_SingleResult_OneResult* mutable_one_result(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ocr_protobuf::OcrResponse_OcrResult_SingleResult_OneResult >*
      mutable_one_result();
  private:
  const ::ocr_protobuf::OcrResponse_OcrResult_SingleResult_OneResult& _internal_one_result(int index) const;
  ::ocr_protobuf::OcrResponse_OcrResult_SingleResult_OneResult* _internal_add_one_result();
  public:
  const ::ocr_protobuf::OcrResponse_OcrResult_SingleResult_OneResult& one_result(int index) const;
  ::ocr_protobuf::OcrResponse_OcrResult_SingleResult_OneResult* add_one_result();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ocr_protobuf::OcrResponse_OcrResult_SingleResult_OneResult >&
      one_result() const;

  // bytes single_str_utf8 = 2;
  void clear_single_str_utf8();
  const std::string& single_str_utf8() const;
  void set_single_str_utf8(const std::string& value);
  void set_single_str_utf8(std::string&& value);
  void set_single_str_utf8(const char* value);
  void set_single_str_utf8(const void* value, size_t size);
  std::string* mutable_single_str_utf8();
  std::string* release_single_str_utf8();
  void set_allocated_single_str_utf8(std::string* single_str_utf8);
  private:
  const std::string& _internal_single_str_utf8() const;
  void _internal_set_single_str_utf8(const std::string& value);
  std::string* _internal_mutable_single_str_utf8();
  public:

  // .ocr_protobuf.OcrResponse.OcrResult.ResultPos single_pos = 1;
  bool has_single_pos() const;
  private:
  bool _internal_has_single_pos() const;
  public:
  void clear_single_pos();
  const ::ocr_protobuf::OcrResponse_OcrResult_ResultPos& single_pos() const;
  ::ocr_protobuf::OcrResponse_OcrResult_ResultPos* release_single_pos();
  ::ocr_protobuf::OcrResponse_OcrResult_ResultPos* mutable_single_pos();
  void set_allocated_single_pos(::ocr_protobuf::OcrResponse_OcrResult_ResultPos* single_pos);
  private:
  const ::ocr_protobuf::OcrResponse_OcrResult_ResultPos& _internal_single_pos() const;
  ::ocr_protobuf::OcrResponse_OcrResult_ResultPos* _internal_mutable_single_pos();
  public:

  // .ocr_protobuf.OcrResponse.OcrResult.ResultPos unknown_pos = 10;
  bool has_unknown_pos() const;
  private:
  bool _internal_has_unknown_pos() const;
  public:
  void clear_unknown_pos();
  const ::ocr_protobuf::OcrResponse_OcrResult_ResultPos& unknown_pos() const;
  ::ocr_protobuf::OcrResponse_OcrResult_ResultPos* release_unknown_pos();
  ::ocr_protobuf::OcrResponse_OcrResult_ResultPos* mutable_unknown_pos();
  void set_allocated_unknown_pos(::ocr_protobuf::OcrResponse_OcrResult_ResultPos* unknown_pos);
  private:
  const ::ocr_protobuf::OcrResponse_OcrResult_ResultPos& _internal_unknown_pos() const;
  ::ocr_protobuf::OcrResponse_OcrResult_ResultPos* _internal_mutable_unknown_pos();
  public:

  // float single_rate = 3;
  void clear_single_rate();
  float single_rate() const;
  void set_single_rate(float value);
  private:
  float _internal_single_rate() const;
  void _internal_set_single_rate(float value);
  public:

  // float lx = 5;
  void clear_lx();
  float lx() const;
  void set_lx(float value);
  private:
  float _internal_lx() const;
  void _internal_set_lx(float value);
  public:

  // float ly = 6;
  void clear_ly();
  float ly() const;
  void set_ly(float value);
  private:
  float _internal_ly() const;
  void _internal_set_ly(float value);
  public:

  // float rx = 7;
  void clear_rx();
  float rx() const;
  void set_rx(float value);
  private:
  float _internal_rx() const;
  void _internal_set_rx(float value);
  public:

  // float ry = 8;
  void clear_ry();
  float ry() const;
  void set_ry(float value);
  private:
  float _internal_ry() const;
  void _internal_set_ry(float value);
  public:

  // int32 unknown_0 = 9;
  void clear_unknown_0();
  ::PROTOBUF_NAMESPACE_ID::int32 unknown_0() const;
  void set_unknown_0(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_unknown_0() const;
  void _internal_set_unknown_0(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:ocr_protobuf.OcrResponse.OcrResult.SingleResult)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ocr_protobuf::OcrResponse_OcrResult_SingleResult_OneResult > one_result_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr single_str_utf8_;
  ::ocr_protobuf::OcrResponse_OcrResult_ResultPos* single_pos_;
  ::ocr_protobuf::OcrResponse_OcrResult_ResultPos* unknown_pos_;
  float single_rate_;
  float lx_;
  float ly_;
  float rx_;
  float ry_;
  ::PROTOBUF_NAMESPACE_ID::int32 unknown_0_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ocr_5fprotobuf_2eproto;
};
// -------------------------------------------------------------------

class OcrResponse_OcrResult :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ocr_protobuf.OcrResponse.OcrResult) */ {
 public:
  OcrResponse_OcrResult();
  virtual ~OcrResponse_OcrResult();

  OcrResponse_OcrResult(const OcrResponse_OcrResult& from);
  OcrResponse_OcrResult(OcrResponse_OcrResult&& from) noexcept
    : OcrResponse_OcrResult() {
    *this = ::std::move(from);
  }

  inline OcrResponse_OcrResult& operator=(const OcrResponse_OcrResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline OcrResponse_OcrResult& operator=(OcrResponse_OcrResult&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const OcrResponse_OcrResult& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const OcrResponse_OcrResult* internal_default_instance() {
    return reinterpret_cast<const OcrResponse_OcrResult*>(
               &_OcrResponse_OcrResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(OcrResponse_OcrResult& a, OcrResponse_OcrResult& b) {
    a.Swap(&b);
  }
  inline void Swap(OcrResponse_OcrResult* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline OcrResponse_OcrResult* New() const final {
    return CreateMaybeMessage<OcrResponse_OcrResult>(nullptr);
  }

  OcrResponse_OcrResult* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<OcrResponse_OcrResult>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const OcrResponse_OcrResult& from);
  void MergeFrom(const OcrResponse_OcrResult& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OcrResponse_OcrResult* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ocr_protobuf.OcrResponse.OcrResult";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ocr_5fprotobuf_2eproto);
    return ::descriptor_table_ocr_5fprotobuf_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef OcrResponse_OcrResult_ResultPos ResultPos;
  typedef OcrResponse_OcrResult_SingleResult SingleResult;

  // accessors -------------------------------------------------------

  enum : int {
    kSingleResultFieldNumber = 1,
    kUnknown1FieldNumber = 2,
    kUnknown2FieldNumber = 3,
  };
  // repeated .ocr_protobuf.OcrResponse.OcrResult.SingleResult single_result = 1;
  int single_result_size() const;
  private:
  int _internal_single_result_size() const;
  public:
  void clear_single_result();
  ::ocr_protobuf::OcrResponse_OcrResult_SingleResult* mutable_single_result(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ocr_protobuf::OcrResponse_OcrResult_SingleResult >*
      mutable_single_result();
  private:
  const ::ocr_protobuf::OcrResponse_OcrResult_SingleResult& _internal_single_result(int index) const;
  ::ocr_protobuf::OcrResponse_OcrResult_SingleResult* _internal_add_single_result();
  public:
  const ::ocr_protobuf::OcrResponse_OcrResult_SingleResult& single_result(int index) const;
  ::ocr_protobuf::OcrResponse_OcrResult_SingleResult* add_single_result();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ocr_protobuf::OcrResponse_OcrResult_SingleResult >&
      single_result() const;

  // int32 unknown_1 = 2;
  void clear_unknown_1();
  ::PROTOBUF_NAMESPACE_ID::int32 unknown_1() const;
  void set_unknown_1(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_unknown_1() const;
  void _internal_set_unknown_1(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 unknown_2 = 3;
  void clear_unknown_2();
  ::PROTOBUF_NAMESPACE_ID::int32 unknown_2() const;
  void set_unknown_2(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_unknown_2() const;
  void _internal_set_unknown_2(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:ocr_protobuf.OcrResponse.OcrResult)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ocr_protobuf::OcrResponse_OcrResult_SingleResult > single_result_;
  ::PROTOBUF_NAMESPACE_ID::int32 unknown_1_;
  ::PROTOBUF_NAMESPACE_ID::int32 unknown_2_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ocr_5fprotobuf_2eproto;
};
// -------------------------------------------------------------------

class OcrResponse :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ocr_protobuf.OcrResponse) */ {
 public:
  OcrResponse();
  virtual ~OcrResponse();

  OcrResponse(const OcrResponse& from);
  OcrResponse(OcrResponse&& from) noexcept
    : OcrResponse() {
    *this = ::std::move(from);
  }

  inline OcrResponse& operator=(const OcrResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline OcrResponse& operator=(OcrResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const OcrResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const OcrResponse* internal_default_instance() {
    return reinterpret_cast<const OcrResponse*>(
               &_OcrResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(OcrResponse& a, OcrResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(OcrResponse* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline OcrResponse* New() const final {
    return CreateMaybeMessage<OcrResponse>(nullptr);
  }

  OcrResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<OcrResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const OcrResponse& from);
  void MergeFrom(const OcrResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OcrResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ocr_protobuf.OcrResponse";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ocr_5fprotobuf_2eproto);
    return ::descriptor_table_ocr_5fprotobuf_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef OcrResponse_OcrResult OcrResult;

  // accessors -------------------------------------------------------

  enum : int {
    kOcrResultFieldNumber = 4,
    kTypeFieldNumber = 1,
    kTaskIdFieldNumber = 2,
    kErrCodeFieldNumber = 3,
  };
  // .ocr_protobuf.OcrResponse.OcrResult ocr_result = 4;
  bool has_ocr_result() const;
  private:
  bool _internal_has_ocr_result() const;
  public:
  void clear_ocr_result();
  const ::ocr_protobuf::OcrResponse_OcrResult& ocr_result() const;
  ::ocr_protobuf::OcrResponse_OcrResult* release_ocr_result();
  ::ocr_protobuf::OcrResponse_OcrResult* mutable_ocr_result();
  void set_allocated_ocr_result(::ocr_protobuf::OcrResponse_OcrResult* ocr_result);
  private:
  const ::ocr_protobuf::OcrResponse_OcrResult& _internal_ocr_result() const;
  ::ocr_protobuf::OcrResponse_OcrResult* _internal_mutable_ocr_result();
  public:

  // int32 type = 1;
  void clear_type();
  ::PROTOBUF_NAMESPACE_ID::int32 type() const;
  void set_type(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_type() const;
  void _internal_set_type(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 task_id = 2;
  void clear_task_id();
  ::PROTOBUF_NAMESPACE_ID::int32 task_id() const;
  void set_task_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_task_id() const;
  void _internal_set_task_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 err_code = 3;
  void clear_err_code();
  ::PROTOBUF_NAMESPACE_ID::int32 err_code() const;
  void set_err_code(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_err_code() const;
  void _internal_set_err_code(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:ocr_protobuf.OcrResponse)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::ocr_protobuf::OcrResponse_OcrResult* ocr_result_;
  ::PROTOBUF_NAMESPACE_ID::int32 type_;
  ::PROTOBUF_NAMESPACE_ID::int32 task_id_;
  ::PROTOBUF_NAMESPACE_ID::int32 err_code_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ocr_5fprotobuf_2eproto;
};
// -------------------------------------------------------------------

class OcrRequest_PicPaths :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ocr_protobuf.OcrRequest.PicPaths) */ {
 public:
  OcrRequest_PicPaths();
  virtual ~OcrRequest_PicPaths();

  OcrRequest_PicPaths(const OcrRequest_PicPaths& from);
  OcrRequest_PicPaths(OcrRequest_PicPaths&& from) noexcept
    : OcrRequest_PicPaths() {
    *this = ::std::move(from);
  }

  inline OcrRequest_PicPaths& operator=(const OcrRequest_PicPaths& from) {
    CopyFrom(from);
    return *this;
  }
  inline OcrRequest_PicPaths& operator=(OcrRequest_PicPaths&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const OcrRequest_PicPaths& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const OcrRequest_PicPaths* internal_default_instance() {
    return reinterpret_cast<const OcrRequest_PicPaths*>(
               &_OcrRequest_PicPaths_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(OcrRequest_PicPaths& a, OcrRequest_PicPaths& b) {
    a.Swap(&b);
  }
  inline void Swap(OcrRequest_PicPaths* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline OcrRequest_PicPaths* New() const final {
    return CreateMaybeMessage<OcrRequest_PicPaths>(nullptr);
  }

  OcrRequest_PicPaths* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<OcrRequest_PicPaths>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const OcrRequest_PicPaths& from);
  void MergeFrom(const OcrRequest_PicPaths& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OcrRequest_PicPaths* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ocr_protobuf.OcrRequest.PicPaths";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ocr_5fprotobuf_2eproto);
    return ::descriptor_table_ocr_5fprotobuf_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPicPathFieldNumber = 1,
  };
  // repeated string pic_path = 1;
  int pic_path_size() const;
  private:
  int _internal_pic_path_size() const;
  public:
  void clear_pic_path();
  const std::string& pic_path(int index) const;
  std::string* mutable_pic_path(int index);
  void set_pic_path(int index, const std::string& value);
  void set_pic_path(int index, std::string&& value);
  void set_pic_path(int index, const char* value);
  void set_pic_path(int index, const char* value, size_t size);
  std::string* add_pic_path();
  void add_pic_path(const std::string& value);
  void add_pic_path(std::string&& value);
  void add_pic_path(const char* value);
  void add_pic_path(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& pic_path() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_pic_path();
  private:
  const std::string& _internal_pic_path(int index) const;
  std::string* _internal_add_pic_path();
  public:

  // @@protoc_insertion_point(class_scope:ocr_protobuf.OcrRequest.PicPaths)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> pic_path_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ocr_5fprotobuf_2eproto;
};
// -------------------------------------------------------------------

class OcrRequest :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ocr_protobuf.OcrRequest) */ {
 public:
  OcrRequest();
  virtual ~OcrRequest();

  OcrRequest(const OcrRequest& from);
  OcrRequest(OcrRequest&& from) noexcept
    : OcrRequest() {
    *this = ::std::move(from);
  }

  inline OcrRequest& operator=(const OcrRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline OcrRequest& operator=(OcrRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const OcrRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const OcrRequest* internal_default_instance() {
    return reinterpret_cast<const OcrRequest*>(
               &_OcrRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(OcrRequest& a, OcrRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(OcrRequest* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline OcrRequest* New() const final {
    return CreateMaybeMessage<OcrRequest>(nullptr);
  }

  OcrRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<OcrRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const OcrRequest& from);
  void MergeFrom(const OcrRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OcrRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ocr_protobuf.OcrRequest";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ocr_5fprotobuf_2eproto);
    return ::descriptor_table_ocr_5fprotobuf_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef OcrRequest_PicPaths PicPaths;

  // accessors -------------------------------------------------------

  enum : int {
    kPicPathFieldNumber = 3,
    kUnknowFieldNumber = 1,
    kTaskIdFieldNumber = 2,
  };
  // .ocr_protobuf.OcrRequest.PicPaths pic_path = 3;
  bool has_pic_path() const;
  private:
  bool _internal_has_pic_path() const;
  public:
  void clear_pic_path();
  const ::ocr_protobuf::OcrRequest_PicPaths& pic_path() const;
  ::ocr_protobuf::OcrRequest_PicPaths* release_pic_path();
  ::ocr_protobuf::OcrRequest_PicPaths* mutable_pic_path();
  void set_allocated_pic_path(::ocr_protobuf::OcrRequest_PicPaths* pic_path);
  private:
  const ::ocr_protobuf::OcrRequest_PicPaths& _internal_pic_path() const;
  ::ocr_protobuf::OcrRequest_PicPaths* _internal_mutable_pic_path();
  public:

  // int32 unknow = 1;
  void clear_unknow();
  ::PROTOBUF_NAMESPACE_ID::int32 unknow() const;
  void set_unknow(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_unknow() const;
  void _internal_set_unknow(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 task_id = 2;
  void clear_task_id();
  ::PROTOBUF_NAMESPACE_ID::int32 task_id() const;
  void set_task_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_task_id() const;
  void _internal_set_task_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:ocr_protobuf.OcrRequest)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::ocr_protobuf::OcrRequest_PicPaths* pic_path_;
  ::PROTOBUF_NAMESPACE_ID::int32 unknow_;
  ::PROTOBUF_NAMESPACE_ID::int32 task_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ocr_5fprotobuf_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// OcrResponse_OcrResult_ResultPos_PosXY

// float x = 1;
inline void OcrResponse_OcrResult_ResultPos_PosXY::clear_x() {
  x_ = 0;
}
inline float OcrResponse_OcrResult_ResultPos_PosXY::_internal_x() const {
  return x_;
}
inline float OcrResponse_OcrResult_ResultPos_PosXY::x() const {
  // @@protoc_insertion_point(field_get:ocr_protobuf.OcrResponse.OcrResult.ResultPos.PosXY.x)
  return _internal_x();
}
inline void OcrResponse_OcrResult_ResultPos_PosXY::_internal_set_x(float value) {
  
  x_ = value;
}
inline void OcrResponse_OcrResult_ResultPos_PosXY::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:ocr_protobuf.OcrResponse.OcrResult.ResultPos.PosXY.x)
}

// float y = 2;
inline void OcrResponse_OcrResult_ResultPos_PosXY::clear_y() {
  y_ = 0;
}
inline float OcrResponse_OcrResult_ResultPos_PosXY::_internal_y() const {
  return y_;
}
inline float OcrResponse_OcrResult_ResultPos_PosXY::y() const {
  // @@protoc_insertion_point(field_get:ocr_protobuf.OcrResponse.OcrResult.ResultPos.PosXY.y)
  return _internal_y();
}
inline void OcrResponse_OcrResult_ResultPos_PosXY::_internal_set_y(float value) {
  
  y_ = value;
}
inline void OcrResponse_OcrResult_ResultPos_PosXY::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:ocr_protobuf.OcrResponse.OcrResult.ResultPos.PosXY.y)
}

// -------------------------------------------------------------------

// OcrResponse_OcrResult_ResultPos

// repeated .ocr_protobuf.OcrResponse.OcrResult.ResultPos.PosXY pos = 1;
inline int OcrResponse_OcrResult_ResultPos::_internal_pos_size() const {
  return pos_.size();
}
inline int OcrResponse_OcrResult_ResultPos::pos_size() const {
  return _internal_pos_size();
}
inline void OcrResponse_OcrResult_ResultPos::clear_pos() {
  pos_.Clear();
}
inline ::ocr_protobuf::OcrResponse_OcrResult_ResultPos_PosXY* OcrResponse_OcrResult_ResultPos::mutable_pos(int index) {
  // @@protoc_insertion_point(field_mutable:ocr_protobuf.OcrResponse.OcrResult.ResultPos.pos)
  return pos_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ocr_protobuf::OcrResponse_OcrResult_ResultPos_PosXY >*
OcrResponse_OcrResult_ResultPos::mutable_pos() {
  // @@protoc_insertion_point(field_mutable_list:ocr_protobuf.OcrResponse.OcrResult.ResultPos.pos)
  return &pos_;
}
inline const ::ocr_protobuf::OcrResponse_OcrResult_ResultPos_PosXY& OcrResponse_OcrResult_ResultPos::_internal_pos(int index) const {
  return pos_.Get(index);
}
inline const ::ocr_protobuf::OcrResponse_OcrResult_ResultPos_PosXY& OcrResponse_OcrResult_ResultPos::pos(int index) const {
  // @@protoc_insertion_point(field_get:ocr_protobuf.OcrResponse.OcrResult.ResultPos.pos)
  return _internal_pos(index);
}
inline ::ocr_protobuf::OcrResponse_OcrResult_ResultPos_PosXY* OcrResponse_OcrResult_ResultPos::_internal_add_pos() {
  return pos_.Add();
}
inline ::ocr_protobuf::OcrResponse_OcrResult_ResultPos_PosXY* OcrResponse_OcrResult_ResultPos::add_pos() {
  // @@protoc_insertion_point(field_add:ocr_protobuf.OcrResponse.OcrResult.ResultPos.pos)
  return _internal_add_pos();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ocr_protobuf::OcrResponse_OcrResult_ResultPos_PosXY >&
OcrResponse_OcrResult_ResultPos::pos() const {
  // @@protoc_insertion_point(field_list:ocr_protobuf.OcrResponse.OcrResult.ResultPos.pos)
  return pos_;
}

// -------------------------------------------------------------------

// OcrResponse_OcrResult_SingleResult_OneResult

// .ocr_protobuf.OcrResponse.OcrResult.ResultPos one_pos = 1;
inline bool OcrResponse_OcrResult_SingleResult_OneResult::_internal_has_one_pos() const {
  return this != internal_default_instance() && one_pos_ != nullptr;
}
inline bool OcrResponse_OcrResult_SingleResult_OneResult::has_one_pos() const {
  return _internal_has_one_pos();
}
inline void OcrResponse_OcrResult_SingleResult_OneResult::clear_one_pos() {
  if (GetArenaNoVirtual() == nullptr && one_pos_ != nullptr) {
    delete one_pos_;
  }
  one_pos_ = nullptr;
}
inline const ::ocr_protobuf::OcrResponse_OcrResult_ResultPos& OcrResponse_OcrResult_SingleResult_OneResult::_internal_one_pos() const {
  const ::ocr_protobuf::OcrResponse_OcrResult_ResultPos* p = one_pos_;
  return p != nullptr ? *p : *reinterpret_cast<const ::ocr_protobuf::OcrResponse_OcrResult_ResultPos*>(
      &::ocr_protobuf::_OcrResponse_OcrResult_ResultPos_default_instance_);
}
inline const ::ocr_protobuf::OcrResponse_OcrResult_ResultPos& OcrResponse_OcrResult_SingleResult_OneResult::one_pos() const {
  // @@protoc_insertion_point(field_get:ocr_protobuf.OcrResponse.OcrResult.SingleResult.OneResult.one_pos)
  return _internal_one_pos();
}
inline ::ocr_protobuf::OcrResponse_OcrResult_ResultPos* OcrResponse_OcrResult_SingleResult_OneResult::release_one_pos() {
  // @@protoc_insertion_point(field_release:ocr_protobuf.OcrResponse.OcrResult.SingleResult.OneResult.one_pos)
  
  ::ocr_protobuf::OcrResponse_OcrResult_ResultPos* temp = one_pos_;
  one_pos_ = nullptr;
  return temp;
}
inline ::ocr_protobuf::OcrResponse_OcrResult_ResultPos* OcrResponse_OcrResult_SingleResult_OneResult::_internal_mutable_one_pos() {
  
  if (one_pos_ == nullptr) {
    auto* p = CreateMaybeMessage<::ocr_protobuf::OcrResponse_OcrResult_ResultPos>(GetArenaNoVirtual());
    one_pos_ = p;
  }
  return one_pos_;
}
inline ::ocr_protobuf::OcrResponse_OcrResult_ResultPos* OcrResponse_OcrResult_SingleResult_OneResult::mutable_one_pos() {
  // @@protoc_insertion_point(field_mutable:ocr_protobuf.OcrResponse.OcrResult.SingleResult.OneResult.one_pos)
  return _internal_mutable_one_pos();
}
inline void OcrResponse_OcrResult_SingleResult_OneResult::set_allocated_one_pos(::ocr_protobuf::OcrResponse_OcrResult_ResultPos* one_pos) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete one_pos_;
  }
  if (one_pos) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      one_pos = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, one_pos, submessage_arena);
    }
    
  } else {
    
  }
  one_pos_ = one_pos;
  // @@protoc_insertion_point(field_set_allocated:ocr_protobuf.OcrResponse.OcrResult.SingleResult.OneResult.one_pos)
}

// bytes one_str_utf8 = 2;
inline void OcrResponse_OcrResult_SingleResult_OneResult::clear_one_str_utf8() {
  one_str_utf8_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& OcrResponse_OcrResult_SingleResult_OneResult::one_str_utf8() const {
  // @@protoc_insertion_point(field_get:ocr_protobuf.OcrResponse.OcrResult.SingleResult.OneResult.one_str_utf8)
  return _internal_one_str_utf8();
}
inline void OcrResponse_OcrResult_SingleResult_OneResult::set_one_str_utf8(const std::string& value) {
  _internal_set_one_str_utf8(value);
  // @@protoc_insertion_point(field_set:ocr_protobuf.OcrResponse.OcrResult.SingleResult.OneResult.one_str_utf8)
}
inline std::string* OcrResponse_OcrResult_SingleResult_OneResult::mutable_one_str_utf8() {
  // @@protoc_insertion_point(field_mutable:ocr_protobuf.OcrResponse.OcrResult.SingleResult.OneResult.one_str_utf8)
  return _internal_mutable_one_str_utf8();
}
inline const std::string& OcrResponse_OcrResult_SingleResult_OneResult::_internal_one_str_utf8() const {
  return one_str_utf8_.GetNoArena();
}
inline void OcrResponse_OcrResult_SingleResult_OneResult::_internal_set_one_str_utf8(const std::string& value) {
  
  one_str_utf8_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void OcrResponse_OcrResult_SingleResult_OneResult::set_one_str_utf8(std::string&& value) {
  
  one_str_utf8_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ocr_protobuf.OcrResponse.OcrResult.SingleResult.OneResult.one_str_utf8)
}
inline void OcrResponse_OcrResult_SingleResult_OneResult::set_one_str_utf8(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  one_str_utf8_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ocr_protobuf.OcrResponse.OcrResult.SingleResult.OneResult.one_str_utf8)
}
inline void OcrResponse_OcrResult_SingleResult_OneResult::set_one_str_utf8(const void* value, size_t size) {
  
  one_str_utf8_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ocr_protobuf.OcrResponse.OcrResult.SingleResult.OneResult.one_str_utf8)
}
inline std::string* OcrResponse_OcrResult_SingleResult_OneResult::_internal_mutable_one_str_utf8() {
  
  return one_str_utf8_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* OcrResponse_OcrResult_SingleResult_OneResult::release_one_str_utf8() {
  // @@protoc_insertion_point(field_release:ocr_protobuf.OcrResponse.OcrResult.SingleResult.OneResult.one_str_utf8)
  
  return one_str_utf8_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void OcrResponse_OcrResult_SingleResult_OneResult::set_allocated_one_str_utf8(std::string* one_str_utf8) {
  if (one_str_utf8 != nullptr) {
    
  } else {
    
  }
  one_str_utf8_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), one_str_utf8);
  // @@protoc_insertion_point(field_set_allocated:ocr_protobuf.OcrResponse.OcrResult.SingleResult.OneResult.one_str_utf8)
}

// -------------------------------------------------------------------

// OcrResponse_OcrResult_SingleResult

// .ocr_protobuf.OcrResponse.OcrResult.ResultPos single_pos = 1;
inline bool OcrResponse_OcrResult_SingleResult::_internal_has_single_pos() const {
  return this != internal_default_instance() && single_pos_ != nullptr;
}
inline bool OcrResponse_OcrResult_SingleResult::has_single_pos() const {
  return _internal_has_single_pos();
}
inline void OcrResponse_OcrResult_SingleResult::clear_single_pos() {
  if (GetArenaNoVirtual() == nullptr && single_pos_ != nullptr) {
    delete single_pos_;
  }
  single_pos_ = nullptr;
}
inline const ::ocr_protobuf::OcrResponse_OcrResult_ResultPos& OcrResponse_OcrResult_SingleResult::_internal_single_pos() const {
  const ::ocr_protobuf::OcrResponse_OcrResult_ResultPos* p = single_pos_;
  return p != nullptr ? *p : *reinterpret_cast<const ::ocr_protobuf::OcrResponse_OcrResult_ResultPos*>(
      &::ocr_protobuf::_OcrResponse_OcrResult_ResultPos_default_instance_);
}
inline const ::ocr_protobuf::OcrResponse_OcrResult_ResultPos& OcrResponse_OcrResult_SingleResult::single_pos() const {
  // @@protoc_insertion_point(field_get:ocr_protobuf.OcrResponse.OcrResult.SingleResult.single_pos)
  return _internal_single_pos();
}
inline ::ocr_protobuf::OcrResponse_OcrResult_ResultPos* OcrResponse_OcrResult_SingleResult::release_single_pos() {
  // @@protoc_insertion_point(field_release:ocr_protobuf.OcrResponse.OcrResult.SingleResult.single_pos)
  
  ::ocr_protobuf::OcrResponse_OcrResult_ResultPos* temp = single_pos_;
  single_pos_ = nullptr;
  return temp;
}
inline ::ocr_protobuf::OcrResponse_OcrResult_ResultPos* OcrResponse_OcrResult_SingleResult::_internal_mutable_single_pos() {
  
  if (single_pos_ == nullptr) {
    auto* p = CreateMaybeMessage<::ocr_protobuf::OcrResponse_OcrResult_ResultPos>(GetArenaNoVirtual());
    single_pos_ = p;
  }
  return single_pos_;
}
inline ::ocr_protobuf::OcrResponse_OcrResult_ResultPos* OcrResponse_OcrResult_SingleResult::mutable_single_pos() {
  // @@protoc_insertion_point(field_mutable:ocr_protobuf.OcrResponse.OcrResult.SingleResult.single_pos)
  return _internal_mutable_single_pos();
}
inline void OcrResponse_OcrResult_SingleResult::set_allocated_single_pos(::ocr_protobuf::OcrResponse_OcrResult_ResultPos* single_pos) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete single_pos_;
  }
  if (single_pos) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      single_pos = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, single_pos, submessage_arena);
    }
    
  } else {
    
  }
  single_pos_ = single_pos;
  // @@protoc_insertion_point(field_set_allocated:ocr_protobuf.OcrResponse.OcrResult.SingleResult.single_pos)
}

// bytes single_str_utf8 = 2;
inline void OcrResponse_OcrResult_SingleResult::clear_single_str_utf8() {
  single_str_utf8_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& OcrResponse_OcrResult_SingleResult::single_str_utf8() const {
  // @@protoc_insertion_point(field_get:ocr_protobuf.OcrResponse.OcrResult.SingleResult.single_str_utf8)
  return _internal_single_str_utf8();
}
inline void OcrResponse_OcrResult_SingleResult::set_single_str_utf8(const std::string& value) {
  _internal_set_single_str_utf8(value);
  // @@protoc_insertion_point(field_set:ocr_protobuf.OcrResponse.OcrResult.SingleResult.single_str_utf8)
}
inline std::string* OcrResponse_OcrResult_SingleResult::mutable_single_str_utf8() {
  // @@protoc_insertion_point(field_mutable:ocr_protobuf.OcrResponse.OcrResult.SingleResult.single_str_utf8)
  return _internal_mutable_single_str_utf8();
}
inline const std::string& OcrResponse_OcrResult_SingleResult::_internal_single_str_utf8() const {
  return single_str_utf8_.GetNoArena();
}
inline void OcrResponse_OcrResult_SingleResult::_internal_set_single_str_utf8(const std::string& value) {
  
  single_str_utf8_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void OcrResponse_OcrResult_SingleResult::set_single_str_utf8(std::string&& value) {
  
  single_str_utf8_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ocr_protobuf.OcrResponse.OcrResult.SingleResult.single_str_utf8)
}
inline void OcrResponse_OcrResult_SingleResult::set_single_str_utf8(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  single_str_utf8_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ocr_protobuf.OcrResponse.OcrResult.SingleResult.single_str_utf8)
}
inline void OcrResponse_OcrResult_SingleResult::set_single_str_utf8(const void* value, size_t size) {
  
  single_str_utf8_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ocr_protobuf.OcrResponse.OcrResult.SingleResult.single_str_utf8)
}
inline std::string* OcrResponse_OcrResult_SingleResult::_internal_mutable_single_str_utf8() {
  
  return single_str_utf8_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* OcrResponse_OcrResult_SingleResult::release_single_str_utf8() {
  // @@protoc_insertion_point(field_release:ocr_protobuf.OcrResponse.OcrResult.SingleResult.single_str_utf8)
  
  return single_str_utf8_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void OcrResponse_OcrResult_SingleResult::set_allocated_single_str_utf8(std::string* single_str_utf8) {
  if (single_str_utf8 != nullptr) {
    
  } else {
    
  }
  single_str_utf8_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), single_str_utf8);
  // @@protoc_insertion_point(field_set_allocated:ocr_protobuf.OcrResponse.OcrResult.SingleResult.single_str_utf8)
}

// float single_rate = 3;
inline void OcrResponse_OcrResult_SingleResult::clear_single_rate() {
  single_rate_ = 0;
}
inline float OcrResponse_OcrResult_SingleResult::_internal_single_rate() const {
  return single_rate_;
}
inline float OcrResponse_OcrResult_SingleResult::single_rate() const {
  // @@protoc_insertion_point(field_get:ocr_protobuf.OcrResponse.OcrResult.SingleResult.single_rate)
  return _internal_single_rate();
}
inline void OcrResponse_OcrResult_SingleResult::_internal_set_single_rate(float value) {
  
  single_rate_ = value;
}
inline void OcrResponse_OcrResult_SingleResult::set_single_rate(float value) {
  _internal_set_single_rate(value);
  // @@protoc_insertion_point(field_set:ocr_protobuf.OcrResponse.OcrResult.SingleResult.single_rate)
}

// repeated .ocr_protobuf.OcrResponse.OcrResult.SingleResult.OneResult one_result = 4;
inline int OcrResponse_OcrResult_SingleResult::_internal_one_result_size() const {
  return one_result_.size();
}
inline int OcrResponse_OcrResult_SingleResult::one_result_size() const {
  return _internal_one_result_size();
}
inline void OcrResponse_OcrResult_SingleResult::clear_one_result() {
  one_result_.Clear();
}
inline ::ocr_protobuf::OcrResponse_OcrResult_SingleResult_OneResult* OcrResponse_OcrResult_SingleResult::mutable_one_result(int index) {
  // @@protoc_insertion_point(field_mutable:ocr_protobuf.OcrResponse.OcrResult.SingleResult.one_result)
  return one_result_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ocr_protobuf::OcrResponse_OcrResult_SingleResult_OneResult >*
OcrResponse_OcrResult_SingleResult::mutable_one_result() {
  // @@protoc_insertion_point(field_mutable_list:ocr_protobuf.OcrResponse.OcrResult.SingleResult.one_result)
  return &one_result_;
}
inline const ::ocr_protobuf::OcrResponse_OcrResult_SingleResult_OneResult& OcrResponse_OcrResult_SingleResult::_internal_one_result(int index) const {
  return one_result_.Get(index);
}
inline const ::ocr_protobuf::OcrResponse_OcrResult_SingleResult_OneResult& OcrResponse_OcrResult_SingleResult::one_result(int index) const {
  // @@protoc_insertion_point(field_get:ocr_protobuf.OcrResponse.OcrResult.SingleResult.one_result)
  return _internal_one_result(index);
}
inline ::ocr_protobuf::OcrResponse_OcrResult_SingleResult_OneResult* OcrResponse_OcrResult_SingleResult::_internal_add_one_result() {
  return one_result_.Add();
}
inline ::ocr_protobuf::OcrResponse_OcrResult_SingleResult_OneResult* OcrResponse_OcrResult_SingleResult::add_one_result() {
  // @@protoc_insertion_point(field_add:ocr_protobuf.OcrResponse.OcrResult.SingleResult.one_result)
  return _internal_add_one_result();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ocr_protobuf::OcrResponse_OcrResult_SingleResult_OneResult >&
OcrResponse_OcrResult_SingleResult::one_result() const {
  // @@protoc_insertion_point(field_list:ocr_protobuf.OcrResponse.OcrResult.SingleResult.one_result)
  return one_result_;
}

// float lx = 5;
inline void OcrResponse_OcrResult_SingleResult::clear_lx() {
  lx_ = 0;
}
inline float OcrResponse_OcrResult_SingleResult::_internal_lx() const {
  return lx_;
}
inline float OcrResponse_OcrResult_SingleResult::lx() const {
  // @@protoc_insertion_point(field_get:ocr_protobuf.OcrResponse.OcrResult.SingleResult.lx)
  return _internal_lx();
}
inline void OcrResponse_OcrResult_SingleResult::_internal_set_lx(float value) {
  
  lx_ = value;
}
inline void OcrResponse_OcrResult_SingleResult::set_lx(float value) {
  _internal_set_lx(value);
  // @@protoc_insertion_point(field_set:ocr_protobuf.OcrResponse.OcrResult.SingleResult.lx)
}

// float ly = 6;
inline void OcrResponse_OcrResult_SingleResult::clear_ly() {
  ly_ = 0;
}
inline float OcrResponse_OcrResult_SingleResult::_internal_ly() const {
  return ly_;
}
inline float OcrResponse_OcrResult_SingleResult::ly() const {
  // @@protoc_insertion_point(field_get:ocr_protobuf.OcrResponse.OcrResult.SingleResult.ly)
  return _internal_ly();
}
inline void OcrResponse_OcrResult_SingleResult::_internal_set_ly(float value) {
  
  ly_ = value;
}
inline void OcrResponse_OcrResult_SingleResult::set_ly(float value) {
  _internal_set_ly(value);
  // @@protoc_insertion_point(field_set:ocr_protobuf.OcrResponse.OcrResult.SingleResult.ly)
}

// float rx = 7;
inline void OcrResponse_OcrResult_SingleResult::clear_rx() {
  rx_ = 0;
}
inline float OcrResponse_OcrResult_SingleResult::_internal_rx() const {
  return rx_;
}
inline float OcrResponse_OcrResult_SingleResult::rx() const {
  // @@protoc_insertion_point(field_get:ocr_protobuf.OcrResponse.OcrResult.SingleResult.rx)
  return _internal_rx();
}
inline void OcrResponse_OcrResult_SingleResult::_internal_set_rx(float value) {
  
  rx_ = value;
}
inline void OcrResponse_OcrResult_SingleResult::set_rx(float value) {
  _internal_set_rx(value);
  // @@protoc_insertion_point(field_set:ocr_protobuf.OcrResponse.OcrResult.SingleResult.rx)
}

// float ry = 8;
inline void OcrResponse_OcrResult_SingleResult::clear_ry() {
  ry_ = 0;
}
inline float OcrResponse_OcrResult_SingleResult::_internal_ry() const {
  return ry_;
}
inline float OcrResponse_OcrResult_SingleResult::ry() const {
  // @@protoc_insertion_point(field_get:ocr_protobuf.OcrResponse.OcrResult.SingleResult.ry)
  return _internal_ry();
}
inline void OcrResponse_OcrResult_SingleResult::_internal_set_ry(float value) {
  
  ry_ = value;
}
inline void OcrResponse_OcrResult_SingleResult::set_ry(float value) {
  _internal_set_ry(value);
  // @@protoc_insertion_point(field_set:ocr_protobuf.OcrResponse.OcrResult.SingleResult.ry)
}

// int32 unknown_0 = 9;
inline void OcrResponse_OcrResult_SingleResult::clear_unknown_0() {
  unknown_0_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 OcrResponse_OcrResult_SingleResult::_internal_unknown_0() const {
  return unknown_0_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 OcrResponse_OcrResult_SingleResult::unknown_0() const {
  // @@protoc_insertion_point(field_get:ocr_protobuf.OcrResponse.OcrResult.SingleResult.unknown_0)
  return _internal_unknown_0();
}
inline void OcrResponse_OcrResult_SingleResult::_internal_set_unknown_0(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  unknown_0_ = value;
}
inline void OcrResponse_OcrResult_SingleResult::set_unknown_0(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_unknown_0(value);
  // @@protoc_insertion_point(field_set:ocr_protobuf.OcrResponse.OcrResult.SingleResult.unknown_0)
}

// .ocr_protobuf.OcrResponse.OcrResult.ResultPos unknown_pos = 10;
inline bool OcrResponse_OcrResult_SingleResult::_internal_has_unknown_pos() const {
  return this != internal_default_instance() && unknown_pos_ != nullptr;
}
inline bool OcrResponse_OcrResult_SingleResult::has_unknown_pos() const {
  return _internal_has_unknown_pos();
}
inline void OcrResponse_OcrResult_SingleResult::clear_unknown_pos() {
  if (GetArenaNoVirtual() == nullptr && unknown_pos_ != nullptr) {
    delete unknown_pos_;
  }
  unknown_pos_ = nullptr;
}
inline const ::ocr_protobuf::OcrResponse_OcrResult_ResultPos& OcrResponse_OcrResult_SingleResult::_internal_unknown_pos() const {
  const ::ocr_protobuf::OcrResponse_OcrResult_ResultPos* p = unknown_pos_;
  return p != nullptr ? *p : *reinterpret_cast<const ::ocr_protobuf::OcrResponse_OcrResult_ResultPos*>(
      &::ocr_protobuf::_OcrResponse_OcrResult_ResultPos_default_instance_);
}
inline const ::ocr_protobuf::OcrResponse_OcrResult_ResultPos& OcrResponse_OcrResult_SingleResult::unknown_pos() const {
  // @@protoc_insertion_point(field_get:ocr_protobuf.OcrResponse.OcrResult.SingleResult.unknown_pos)
  return _internal_unknown_pos();
}
inline ::ocr_protobuf::OcrResponse_OcrResult_ResultPos* OcrResponse_OcrResult_SingleResult::release_unknown_pos() {
  // @@protoc_insertion_point(field_release:ocr_protobuf.OcrResponse.OcrResult.SingleResult.unknown_pos)
  
  ::ocr_protobuf::OcrResponse_OcrResult_ResultPos* temp = unknown_pos_;
  unknown_pos_ = nullptr;
  return temp;
}
inline ::ocr_protobuf::OcrResponse_OcrResult_ResultPos* OcrResponse_OcrResult_SingleResult::_internal_mutable_unknown_pos() {
  
  if (unknown_pos_ == nullptr) {
    auto* p = CreateMaybeMessage<::ocr_protobuf::OcrResponse_OcrResult_ResultPos>(GetArenaNoVirtual());
    unknown_pos_ = p;
  }
  return unknown_pos_;
}
inline ::ocr_protobuf::OcrResponse_OcrResult_ResultPos* OcrResponse_OcrResult_SingleResult::mutable_unknown_pos() {
  // @@protoc_insertion_point(field_mutable:ocr_protobuf.OcrResponse.OcrResult.SingleResult.unknown_pos)
  return _internal_mutable_unknown_pos();
}
inline void OcrResponse_OcrResult_SingleResult::set_allocated_unknown_pos(::ocr_protobuf::OcrResponse_OcrResult_ResultPos* unknown_pos) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete unknown_pos_;
  }
  if (unknown_pos) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      unknown_pos = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, unknown_pos, submessage_arena);
    }
    
  } else {
    
  }
  unknown_pos_ = unknown_pos;
  // @@protoc_insertion_point(field_set_allocated:ocr_protobuf.OcrResponse.OcrResult.SingleResult.unknown_pos)
}

// -------------------------------------------------------------------

// OcrResponse_OcrResult

// repeated .ocr_protobuf.OcrResponse.OcrResult.SingleResult single_result = 1;
inline int OcrResponse_OcrResult::_internal_single_result_size() const {
  return single_result_.size();
}
inline int OcrResponse_OcrResult::single_result_size() const {
  return _internal_single_result_size();
}
inline void OcrResponse_OcrResult::clear_single_result() {
  single_result_.Clear();
}
inline ::ocr_protobuf::OcrResponse_OcrResult_SingleResult* OcrResponse_OcrResult::mutable_single_result(int index) {
  // @@protoc_insertion_point(field_mutable:ocr_protobuf.OcrResponse.OcrResult.single_result)
  return single_result_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ocr_protobuf::OcrResponse_OcrResult_SingleResult >*
OcrResponse_OcrResult::mutable_single_result() {
  // @@protoc_insertion_point(field_mutable_list:ocr_protobuf.OcrResponse.OcrResult.single_result)
  return &single_result_;
}
inline const ::ocr_protobuf::OcrResponse_OcrResult_SingleResult& OcrResponse_OcrResult::_internal_single_result(int index) const {
  return single_result_.Get(index);
}
inline const ::ocr_protobuf::OcrResponse_OcrResult_SingleResult& OcrResponse_OcrResult::single_result(int index) const {
  // @@protoc_insertion_point(field_get:ocr_protobuf.OcrResponse.OcrResult.single_result)
  return _internal_single_result(index);
}
inline ::ocr_protobuf::OcrResponse_OcrResult_SingleResult* OcrResponse_OcrResult::_internal_add_single_result() {
  return single_result_.Add();
}
inline ::ocr_protobuf::OcrResponse_OcrResult_SingleResult* OcrResponse_OcrResult::add_single_result() {
  // @@protoc_insertion_point(field_add:ocr_protobuf.OcrResponse.OcrResult.single_result)
  return _internal_add_single_result();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ocr_protobuf::OcrResponse_OcrResult_SingleResult >&
OcrResponse_OcrResult::single_result() const {
  // @@protoc_insertion_point(field_list:ocr_protobuf.OcrResponse.OcrResult.single_result)
  return single_result_;
}

// int32 unknown_1 = 2;
inline void OcrResponse_OcrResult::clear_unknown_1() {
  unknown_1_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 OcrResponse_OcrResult::_internal_unknown_1() const {
  return unknown_1_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 OcrResponse_OcrResult::unknown_1() const {
  // @@protoc_insertion_point(field_get:ocr_protobuf.OcrResponse.OcrResult.unknown_1)
  return _internal_unknown_1();
}
inline void OcrResponse_OcrResult::_internal_set_unknown_1(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  unknown_1_ = value;
}
inline void OcrResponse_OcrResult::set_unknown_1(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_unknown_1(value);
  // @@protoc_insertion_point(field_set:ocr_protobuf.OcrResponse.OcrResult.unknown_1)
}

// int32 unknown_2 = 3;
inline void OcrResponse_OcrResult::clear_unknown_2() {
  unknown_2_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 OcrResponse_OcrResult::_internal_unknown_2() const {
  return unknown_2_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 OcrResponse_OcrResult::unknown_2() const {
  // @@protoc_insertion_point(field_get:ocr_protobuf.OcrResponse.OcrResult.unknown_2)
  return _internal_unknown_2();
}
inline void OcrResponse_OcrResult::_internal_set_unknown_2(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  unknown_2_ = value;
}
inline void OcrResponse_OcrResult::set_unknown_2(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_unknown_2(value);
  // @@protoc_insertion_point(field_set:ocr_protobuf.OcrResponse.OcrResult.unknown_2)
}

// -------------------------------------------------------------------

// OcrResponse

// int32 type = 1;
inline void OcrResponse::clear_type() {
  type_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 OcrResponse::_internal_type() const {
  return type_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 OcrResponse::type() const {
  // @@protoc_insertion_point(field_get:ocr_protobuf.OcrResponse.type)
  return _internal_type();
}
inline void OcrResponse::_internal_set_type(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  type_ = value;
}
inline void OcrResponse::set_type(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:ocr_protobuf.OcrResponse.type)
}

// int32 task_id = 2;
inline void OcrResponse::clear_task_id() {
  task_id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 OcrResponse::_internal_task_id() const {
  return task_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 OcrResponse::task_id() const {
  // @@protoc_insertion_point(field_get:ocr_protobuf.OcrResponse.task_id)
  return _internal_task_id();
}
inline void OcrResponse::_internal_set_task_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  task_id_ = value;
}
inline void OcrResponse::set_task_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_task_id(value);
  // @@protoc_insertion_point(field_set:ocr_protobuf.OcrResponse.task_id)
}

// int32 err_code = 3;
inline void OcrResponse::clear_err_code() {
  err_code_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 OcrResponse::_internal_err_code() const {
  return err_code_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 OcrResponse::err_code() const {
  // @@protoc_insertion_point(field_get:ocr_protobuf.OcrResponse.err_code)
  return _internal_err_code();
}
inline void OcrResponse::_internal_set_err_code(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  err_code_ = value;
}
inline void OcrResponse::set_err_code(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_err_code(value);
  // @@protoc_insertion_point(field_set:ocr_protobuf.OcrResponse.err_code)
}

// .ocr_protobuf.OcrResponse.OcrResult ocr_result = 4;
inline bool OcrResponse::_internal_has_ocr_result() const {
  return this != internal_default_instance() && ocr_result_ != nullptr;
}
inline bool OcrResponse::has_ocr_result() const {
  return _internal_has_ocr_result();
}
inline void OcrResponse::clear_ocr_result() {
  if (GetArenaNoVirtual() == nullptr && ocr_result_ != nullptr) {
    delete ocr_result_;
  }
  ocr_result_ = nullptr;
}
inline const ::ocr_protobuf::OcrResponse_OcrResult& OcrResponse::_internal_ocr_result() const {
  const ::ocr_protobuf::OcrResponse_OcrResult* p = ocr_result_;
  return p != nullptr ? *p : *reinterpret_cast<const ::ocr_protobuf::OcrResponse_OcrResult*>(
      &::ocr_protobuf::_OcrResponse_OcrResult_default_instance_);
}
inline const ::ocr_protobuf::OcrResponse_OcrResult& OcrResponse::ocr_result() const {
  // @@protoc_insertion_point(field_get:ocr_protobuf.OcrResponse.ocr_result)
  return _internal_ocr_result();
}
inline ::ocr_protobuf::OcrResponse_OcrResult* OcrResponse::release_ocr_result() {
  // @@protoc_insertion_point(field_release:ocr_protobuf.OcrResponse.ocr_result)
  
  ::ocr_protobuf::OcrResponse_OcrResult* temp = ocr_result_;
  ocr_result_ = nullptr;
  return temp;
}
inline ::ocr_protobuf::OcrResponse_OcrResult* OcrResponse::_internal_mutable_ocr_result() {
  
  if (ocr_result_ == nullptr) {
    auto* p = CreateMaybeMessage<::ocr_protobuf::OcrResponse_OcrResult>(GetArenaNoVirtual());
    ocr_result_ = p;
  }
  return ocr_result_;
}
inline ::ocr_protobuf::OcrResponse_OcrResult* OcrResponse::mutable_ocr_result() {
  // @@protoc_insertion_point(field_mutable:ocr_protobuf.OcrResponse.ocr_result)
  return _internal_mutable_ocr_result();
}
inline void OcrResponse::set_allocated_ocr_result(::ocr_protobuf::OcrResponse_OcrResult* ocr_result) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete ocr_result_;
  }
  if (ocr_result) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      ocr_result = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, ocr_result, submessage_arena);
    }
    
  } else {
    
  }
  ocr_result_ = ocr_result;
  // @@protoc_insertion_point(field_set_allocated:ocr_protobuf.OcrResponse.ocr_result)
}

// -------------------------------------------------------------------

// OcrRequest_PicPaths

// repeated string pic_path = 1;
inline int OcrRequest_PicPaths::_internal_pic_path_size() const {
  return pic_path_.size();
}
inline int OcrRequest_PicPaths::pic_path_size() const {
  return _internal_pic_path_size();
}
inline void OcrRequest_PicPaths::clear_pic_path() {
  pic_path_.Clear();
}
inline std::string* OcrRequest_PicPaths::add_pic_path() {
  // @@protoc_insertion_point(field_add_mutable:ocr_protobuf.OcrRequest.PicPaths.pic_path)
  return _internal_add_pic_path();
}
inline const std::string& OcrRequest_PicPaths::_internal_pic_path(int index) const {
  return pic_path_.Get(index);
}
inline const std::string& OcrRequest_PicPaths::pic_path(int index) const {
  // @@protoc_insertion_point(field_get:ocr_protobuf.OcrRequest.PicPaths.pic_path)
  return _internal_pic_path(index);
}
inline std::string* OcrRequest_PicPaths::mutable_pic_path(int index) {
  // @@protoc_insertion_point(field_mutable:ocr_protobuf.OcrRequest.PicPaths.pic_path)
  return pic_path_.Mutable(index);
}
inline void OcrRequest_PicPaths::set_pic_path(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:ocr_protobuf.OcrRequest.PicPaths.pic_path)
  pic_path_.Mutable(index)->assign(value);
}
inline void OcrRequest_PicPaths::set_pic_path(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:ocr_protobuf.OcrRequest.PicPaths.pic_path)
  pic_path_.Mutable(index)->assign(std::move(value));
}
inline void OcrRequest_PicPaths::set_pic_path(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  pic_path_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:ocr_protobuf.OcrRequest.PicPaths.pic_path)
}
inline void OcrRequest_PicPaths::set_pic_path(int index, const char* value, size_t size) {
  pic_path_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:ocr_protobuf.OcrRequest.PicPaths.pic_path)
}
inline std::string* OcrRequest_PicPaths::_internal_add_pic_path() {
  return pic_path_.Add();
}
inline void OcrRequest_PicPaths::add_pic_path(const std::string& value) {
  pic_path_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:ocr_protobuf.OcrRequest.PicPaths.pic_path)
}
inline void OcrRequest_PicPaths::add_pic_path(std::string&& value) {
  pic_path_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:ocr_protobuf.OcrRequest.PicPaths.pic_path)
}
inline void OcrRequest_PicPaths::add_pic_path(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  pic_path_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:ocr_protobuf.OcrRequest.PicPaths.pic_path)
}
inline void OcrRequest_PicPaths::add_pic_path(const char* value, size_t size) {
  pic_path_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:ocr_protobuf.OcrRequest.PicPaths.pic_path)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
OcrRequest_PicPaths::pic_path() const {
  // @@protoc_insertion_point(field_list:ocr_protobuf.OcrRequest.PicPaths.pic_path)
  return pic_path_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
OcrRequest_PicPaths::mutable_pic_path() {
  // @@protoc_insertion_point(field_mutable_list:ocr_protobuf.OcrRequest.PicPaths.pic_path)
  return &pic_path_;
}

// -------------------------------------------------------------------

// OcrRequest

// int32 unknow = 1;
inline void OcrRequest::clear_unknow() {
  unknow_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 OcrRequest::_internal_unknow() const {
  return unknow_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 OcrRequest::unknow() const {
  // @@protoc_insertion_point(field_get:ocr_protobuf.OcrRequest.unknow)
  return _internal_unknow();
}
inline void OcrRequest::_internal_set_unknow(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  unknow_ = value;
}
inline void OcrRequest::set_unknow(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_unknow(value);
  // @@protoc_insertion_point(field_set:ocr_protobuf.OcrRequest.unknow)
}

// int32 task_id = 2;
inline void OcrRequest::clear_task_id() {
  task_id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 OcrRequest::_internal_task_id() const {
  return task_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 OcrRequest::task_id() const {
  // @@protoc_insertion_point(field_get:ocr_protobuf.OcrRequest.task_id)
  return _internal_task_id();
}
inline void OcrRequest::_internal_set_task_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  task_id_ = value;
}
inline void OcrRequest::set_task_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_task_id(value);
  // @@protoc_insertion_point(field_set:ocr_protobuf.OcrRequest.task_id)
}

// .ocr_protobuf.OcrRequest.PicPaths pic_path = 3;
inline bool OcrRequest::_internal_has_pic_path() const {
  return this != internal_default_instance() && pic_path_ != nullptr;
}
inline bool OcrRequest::has_pic_path() const {
  return _internal_has_pic_path();
}
inline void OcrRequest::clear_pic_path() {
  if (GetArenaNoVirtual() == nullptr && pic_path_ != nullptr) {
    delete pic_path_;
  }
  pic_path_ = nullptr;
}
inline const ::ocr_protobuf::OcrRequest_PicPaths& OcrRequest::_internal_pic_path() const {
  const ::ocr_protobuf::OcrRequest_PicPaths* p = pic_path_;
  return p != nullptr ? *p : *reinterpret_cast<const ::ocr_protobuf::OcrRequest_PicPaths*>(
      &::ocr_protobuf::_OcrRequest_PicPaths_default_instance_);
}
inline const ::ocr_protobuf::OcrRequest_PicPaths& OcrRequest::pic_path() const {
  // @@protoc_insertion_point(field_get:ocr_protobuf.OcrRequest.pic_path)
  return _internal_pic_path();
}
inline ::ocr_protobuf::OcrRequest_PicPaths* OcrRequest::release_pic_path() {
  // @@protoc_insertion_point(field_release:ocr_protobuf.OcrRequest.pic_path)
  
  ::ocr_protobuf::OcrRequest_PicPaths* temp = pic_path_;
  pic_path_ = nullptr;
  return temp;
}
inline ::ocr_protobuf::OcrRequest_PicPaths* OcrRequest::_internal_mutable_pic_path() {
  
  if (pic_path_ == nullptr) {
    auto* p = CreateMaybeMessage<::ocr_protobuf::OcrRequest_PicPaths>(GetArenaNoVirtual());
    pic_path_ = p;
  }
  return pic_path_;
}
inline ::ocr_protobuf::OcrRequest_PicPaths* OcrRequest::mutable_pic_path() {
  // @@protoc_insertion_point(field_mutable:ocr_protobuf.OcrRequest.pic_path)
  return _internal_mutable_pic_path();
}
inline void OcrRequest::set_allocated_pic_path(::ocr_protobuf::OcrRequest_PicPaths* pic_path) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete pic_path_;
  }
  if (pic_path) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      pic_path = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, pic_path, submessage_arena);
    }
    
  } else {
    
  }
  pic_path_ = pic_path;
  // @@protoc_insertion_point(field_set_allocated:ocr_protobuf.OcrRequest.pic_path)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ocr_protobuf

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ocr_5fprotobuf_2eproto
